-- MSSV: 20127335
-- TOPIC: 02

-- BƯỚC 1: TẠO CƠ SỞ DỮ LIỆU
USE master -- CHUYỂN CSDL MẶC ĐỊNH VỀ MASTER CỦA HỆ THỐNG
GO  -- KẾT THÚC KHỐI LỆNH Ở TRÊN

IF DB_ID('QLChuyenBay') IS NOT NULL -- KIỂM TRA XEM CÓ TỒN TẠI CSDL QLCHUYENBAY HAY KHÔNG 
    DROP DATABASE QLChuyenBay  -- XOÁ CƠ SỞ DỮ LIỆU
GO

CREATE DATABASE QLCHUYENBAY
GO

USE QLCHUYENBAY
GO

-- BƯỚC 2: TẠO BẢNG VÀ KHOÁ CHÍNH
CREATE TABLE KHACHHANG
(
    -- KHAI BÁO THUỘC TÍNH TRONG BẢNG
    MAKH VARCHAR(15),
    TEN VARCHAR(15),
    DCHI VARCHAR(50),
    DIENTHOAI VARCHAR(12)

    -- TẠO KHOÁ CHÍNH
    CONSTRAINT PK_KHACHHANG -- CÂU LỆNH ĐẶT TÊN KHOÁ
    PRIMARY KEY (MAKH) -- CÂU LỆNH TẠO KHOÁ CHÍNH
)

CREATE TABLE DATCHO
(
    MAKH VARCHAR(15),
    NGAYDI DATE,
    MACB VARCHAR(4)

    CONSTRAINT PK_DATCHO
    PRIMARY KEY (MAKH, NGAYDI, MACB)
)

CREATE TABLE LICHBAY
(
    NGAYDI DATE,
    MACB VARCHAR(4),
    SOHIEU INT,
    MALOAI VARCHAR(15)
    
    CONSTRAINT PK_LICHBAY
    PRIMARY KEY (NGAYDI, MACB)
)

CREATE TABLE CHUYENBAY
(
    MACB VARCHAR(4),
    SBDI VARCHAR(3),
    SBDEN VARCHAR(3),
    GIODI TIME(7),
    GIODEN TIME(7)

    CONSTRAINT PK_CHUYENBAY
    PRIMARY KEY (MACB)
)

CREATE TABLE MAYBAY
(
    SOHIEU INT,
    MALOAI VARCHAR(15)

    CONSTRAINT PK_MAYBAY
    PRIMARY KEY (SOHIEU, MALOAI)
)

CREATE TABLE LOAIMB
(
    HANGSX VARCHAR(15),
    MALOAI VARCHAR(15)

    CONSTRAINT PK_LOAIMB
    PRIMARY KEY (MALOAI)
)

CREATE TABLE KHANANG
(
    MANV VARCHAR(15),
    MALOAI VARCHAR(15)

    CONSTRAINT PK_KHANANG
    PRIMARY KEY (MANV, MALOAI)
)

CREATE TABLE NHANVIEN 
(
    MANV VARCHAR(15),
    TEN VARCHAR(15),
    DCHI VARCHAR(50),
    DTHOAI VARCHAR(12),
    LUONG DECIMAL(10, 2),
    LOAINV BIT

    CONSTRAINT PK_NHANVIEN
    PRIMARY KEY (MANV)
)

CREATE TABLE PHANCONG
(
    MANV VARCHAR(15),
    NGAYDI DATE,
    MACB VARCHAR(4)

    CONSTRAINT PK_PHANCONG
    PRIMARY KEY (MANV, NGAYDI, MACB)
)

-- BƯỚC 3: TẠO KHOÁ NGOẠI (DÃY LIÊN KẾT)
ALTER TABLE DATCHO -- BẢNG ĐẦU Ở VÔ CỰC
ADD
    CONSTRAINT FK_DATCHO_KHACHHANG -- ĐẶT TÊN CHO KHOÁ
    FOREIGN KEY (MAKH) -- THUỘC TÍNH CỦA BẢNG ALTER
    REFERENCES KHACHHANG, -- BẢNG Ở ĐẦU CHÌA KHOÁ

    CONSTRAINT FK_DATCHO_LICHBAY
    FOREIGN KEY (NGAYDI, MACB)
    REFERENCES LICHBAY

ALTER TABLE LICHBAY
ADD
    CONSTRAINT FK_LICHBAY_CHUYENBAY
    FOREIGN KEY (MACB)
    REFERENCES CHUYENBAY,

    CONSTRAINT FK_LICHBAY_CHUYENBAY
    FOREIGN KEY (SOHIEU)
    REFERENCES CHUYENBAY

ALTER TABLE MAYBAY
ADD
    CONSTRAINT FK_MAYBAY_LOAIMB
    FOREIGN KEY (MALOAI)
    REFERENCES LOAIMB

ALTER TABLE KHANANG
ADD
    CONSTRAINT FK_KHANANG_NHANVIEN
    FOREIGN KEY (MANV)
    REFERENCES NHANVIEN,

    CONSTRAINT FK_KHANANG_LOAIMB
    FOREIGN KEY (MALOAI)
    REFERENCES LOAIMB


ALTER TABLE PHANCONG
ADD
    CONSTRAINT FK_PHANCONG_NHANVIEN
    FOREIGN KEY (MANV)
    REFERENCES NHANVIEN,

    CONSTRAINT FK_PHANCONG_LICHBAY
    FOREIGN KEY (NGAYDI, MACB)
    REFERENCES CHUYENBAY


-- BƯỚC 4: NHẬP LIỆU. BẢNG Ở ĐẦU CHÌA KHOÁ NHẬP TRƯỚC RỒI MỚI TỚI ĐẦU VÔ CỰC

-- CHUỖI KHÔNG DẤU: ĐỂ TRONG NHÁY ĐƠN 'ABC'
-- SỐ: NHẬP BÌNH THƯỜNG 3; 2.5
-- KIỂU NGÀY: THEO ĐỊNH DẠNG 'YYYY-MM-DD'
-- KIỂU GIỜ: THEO ĐỊNH DẠNG 'HH:MM:SS'

INSERT KHACHHANG (MAKH, TEN, DCHI, DIENTHOAI)
VALUES ('0009', 'Nga', '223 Nguyen Trai', '8932320'),
       ('0101', 'Anh', '567 Tran Phu', '8826729'), 
       ('0045', 'Thu', '285 Le Loi', '8932203'),
       ('0012', 'Ha', '435 Quang Trung', '8933232'),
       ('0238', 'Hung', '456 Pasteur', '9812101'),
       ('0397', 'Thanh', '234 Le Van Si', '8952943'),
       ('0582', 'Mai', '789 Nguyen Du', NULL),
       ('0934', 'Minh', '678 Le Lai', NULL),
       ('0091', 'Hai', '345 Hung Vuong', '8893223'),
       ('0314', 'Phuong', '395 Vo Van Tan', '8232320'),
       ('0613', 'Vu', '348 CMT8', '8343232'),
       ('0586', 'Son', '123 Bach Dang', '8556223'),
       ('0422', 'Tien', '75 Nguyen Thong', '8332222')

SELECT * FROM KHACHHANG
--CẬP NHẬT DỮ LIỆU (CHỈ DÙNG KHI CẦN THIẾT)
UPDATE KHACHHANG 
SET TEN = 'AAA', DCHI = 'BBB'
WHERE MAKH = '1111' -- ĐIỀU KIỆN ĐỂ TÌM DÒNG CẬP NHẬT

-- XOÁ DÒNG BỊ SAI
DELETE KHACHHANG
WHERE MAKH = '1111'

--TRUY VẤN GOM NHÓM
SELECT COUNT(*) FROM DETAI --> CÓ BAO NHIÊU ĐỀ TÀI
-- ĐẾM SỐ ĐỀ TÀI THEO TỪNG CHỦ ĐỀ
-- CĐ1 = ?
-- CĐ2 = ?
SELECT CD.MACD, TENCD, COUNT(*) AS 'SỐ ĐỀ TÀI'
FROM DETAI DT, CHUDE CD
WHERE DT.MACD = CD.MACD
GROUP BY CD.MACD, TENCD

SELECT * FROM DETAI

