USE master
GO

IF DB_ID('QLDETAI') IS NOT NULL 
    DROP DATABASE QLDETAI
GO

CREATE DATABASE QLDETAI
GO

USE QLDETAI
GO

CREATE TABLE THAMGIADT
(
	MAGV VARCHAR(3),
	MADT VARCHAR(3),
	STT INT,
	PHUCAP FLOAT,
	KETQUA NVARCHAR(3)

	CONSTRAINT PK_THAMGIADT
	PRIMARY KEY (MAGV, MADT, STT)
)

CREATE TABLE CONGVIEC
(
	MADT VARCHAR(3),
	SOTT INT,
	TENCV NVARCHAR(50),
	NGAYBD DATE,
	NGAYKT DATE

	CONSTRAINT PK_CONGVIEC
	PRIMARY KEY (MADT, SOTT)
)

CREATE TABLE DETAI
(
	MADT VARCHAR(3),
	TENDT NVARCHAR(50),
	CAPQL NVARCHAR(10),
	KINHPHI DECIMAL(10, 1),
	NGAYBD DATE,
	NGAYKT DATE, 
	MACD NVARCHAR(4), 
	GVCNDT VARCHAR(3)

	CONSTRAINT PK_DETAI
	PRIMARY KEY (MADT)
)

CREATE TABLE CHUDE
(
	MACD NVARCHAR(4),
	TENCD NVARCHAR(50)

	CONSTRAINT PK_CHUDE
	PRIMARY KEY (MACD)
)

CREATE TABLE KHOA
(
    MAKHOA VARCHAR(4),
    TENKHOA NVARCHAR(20),
    NAMTL DATE,
    PHONG VARCHAR(3),
    DIENTHOAI VARCHAR(10), 
    TRUONGKHOA VARCHAR(3),
    NGAYNHANCHUC DATE

    CONSTRAINT PK_KHOA
    PRIMARY KEY (MAKHOA)
)

CREATE TABLE GIAOVIEN
(
	MAGV VARCHAR(3),
	HOTEN NVARCHAR(20),
	LUONG DECIMAL(10, 1),
	PHAI VARCHAR(3),
	NGAYSINH DATE,
	DIACHI NVARCHAR(50),
	GVQLBM VARCHAR(3), 
	MABM NVARCHAR(4)

	CONSTRAINT PK_GIAOVIEN
	PRIMARY KEY (MAGV)
)

CREATE TABLE NGUOITHAN
(
    MAGV VARCHAR(3), 
    TEN NVARCHAR(20), 
    NGSINH DATE,
    PHAI VARCHAR(3)

    CONSTRAINT PK_NGUOITHAN
    PRIMARY KEY (MAGV, TEN)
)

CREATE TABLE BOMON
(
    MABM NVARCHAR(4), 
    TENBM NVARCHAR(20),
    PHONG VARCHAR(3), 
    DIENTHOAI VARCHAR(10), 
    TRUONGBM VARCHAR(3),
    MAKHOA VARCHAR(4),
    NGAYNHANCHUC DATE

    CONSTRAINT PK_BOMON
    PRIMARY KEY (MABM)
)

CREATE TABLE GV_DT
(
	MAGV VARCHAR(3), 
	DIENTHOAI VARCHAR(10)

	CONSTRAINT PK_GV_DT
	PRIMARY KEY (MAGV, DIENTHOAI)
)

ALTER TABLE THAMGIADT 
ADD 
	CONSTRAINT FK_THAMGIADT_GIAOVIEN
	FOREIGN KEY (MAGV)
	REFERENCES GIAOVIEN,

	CONSTRAINT FK_THAMGIADT_CONGVIEC
	FOREIGN KEY (MADT, STT)
	REFERENCES CONGVIEC

ALTER TABLE CONGVIEC
ADD
	CONSTRAINT FK_CONGVIEC_DETAI
	FOREIGN KEY (MADT)
	REFERENCES DETAI

ALTER TABLE DETAI
ADD
	CONSTRAINT FK_DETAI_CHUDE
	FOREIGN KEY (MACD)
	REFERENCES CHUDE,

	CONSTRAINT FK_DETAI_GIAOVIEN
	FOREIGN KEY (GVCNDT)
	REFERENCES GIAOVIEN

ALTER TABLE KHOA
ADD
	CONSTRAINT FK_KHOA_GIAOVIEN
	FOREIGN KEY (TRUONGKHOA)
	REFERENCES GIAOVIEN

ALTER TABLE BOMON
ADD
	CONSTRAINT FK_BOMON_KHOA
	FOREIGN KEY (MAKHOA)
	REFERENCES KHOA,

	CONSTRAINT FK_BOMON_GIAOVIEN
	FOREIGN KEY (TRUONGBM)
	REFERENCES GIAOVIEN

ALTER TABLE NGUOITHAN
ADD
	CONSTRAINT FK_NGUOITHAN_GIAOVIEN
	FOREIGN KEY (MAGV)
	REFERENCES GIAOVIEN

ALTER TABLE GV_DT
ADD
	CONSTRAINT FK_GV_DT_GIAOVIEN
	FOREIGN KEY (MAGV)
	REFERENCES GIAOVIEN

ALTER TABLE GIAOVIEN
ADD
	CONSTRAINT FK_GIAOVIEN_BOMON
	FOREIGN KEY (MABM)
	REFERENCES BOMON,

	CONSTRAINT FK_GIAOVIEN_GIAOVIEN
	FOREIGN KEY (GVQLBM)
	REFERENCES GIAOVIEN
