-- MSSV: 20127335
-- TOPIC: 03

USE QLCHUYENBAY
GO

-- CÂU 1
SELECT KN.MANV, TEN, DCHI, DTHOAI
FROM NHANVIEN NV, KHANANG KN
WHERE MALOAI = 'B747' 
AND KN.MANV = NV.MANV 
AND NV.LOAINV = 1

-- CÂU 2
SELECT LB.MACB, NGAYDI
FROM LICHBAY LB, CHUYENBAY CB
WHERE CB.SBDI = 'DCA' 
AND GIODI BETWEEN '14:00' AND '18:00' 
AND LB.MACB = CB.MACB

-- CÂU 3
SELECT DISTINCT TEN 
FROM NHANVIEN NV, PHANCONG PC, LICHBAY LB, CHUYENBAY CB
WHERE CB.MACB = '100' 
AND CB.SBDI = 'SLC' 
AND NV.MANV = PC.MANV 
AND PC.MACB = CB.MACB 
AND PC.NGAYDI = LB.NGAYDI
AND LB.MACB = CB.MACB

-- CÂU 4
SELECT DISTINCT MB.MALOAI, MB.SOHIEU
FROM MAYBAY MB, CHUYENBAY CB, LICHBAY LB
WHERE CB.MACB = LB.MACB 
AND LB.MALOAI = MB.MALOAI 
AND LB.SOHIEU = MB.SOHIEU 
AND CB.SBDI = 'MIA'

-- CÂU 5
SELECT MACB, NGAYDI, TEN, DCHI, DIENTHOAI
FROM KHACHHANG KH, DATCHO DC
WHERE KH.MAKH = DC.MAKH
ORDER BY MACB ASC, NGAYDI DESC

-- CÂU 6
SELECT MACB, NGAYDI, TEN, DCHI, DTHOAI
FROM NHANVIEN NV, PHANCONG PC
WHERE NV.MANV = PC.MANV
ORDER BY MACB ASC, NGAYDI DESC

-- CÂU 7
SELECT PC.MACB, PC.NGAYDI, NV.MANV, TEN
FROM NHANVIEN NV, PHANCONG PC, LICHBAY LB, CHUYENBAY CB
WHERE NV.MANV = PC.MANV 
AND PC.NGAYDI = LB.NGAYDI 
AND PC.MACB = LB.MACB 
AND LB.MACB = CB.MACB
AND CB.SBDEN = 'ORD' 
AND NV.LOAINV = 1

-- CÂU 8
SELECT MACB, NGAYDI, TEN
FROM NHANVIEN NV, PHANCONG PC
WHERE NV.MANV = PC.MANV AND NV.MANV = '1001'

-- CÂU 9
SELECT LB.MACB, SBDI, GIODI, GIODEN, NGAYDI
FROM LICHBAY LB, CHUYENBAY CB
WHERE LB.MACB = CB.MACB AND SBDEN = 'DEN'
ORDER BY NGAYDI DESC, SBDI ASC

-- CÂU 10
SELECT TEN, HANGSX, LMB.MALOAI 
FROM LOAIMB LMB, KHANANG KN, NHANVIEN NV
WHERE LMB.MALOAI = KN.MALOAI 
AND NV.MANV = KN.MANV 
AND NV.LOAINV = 1

-- CÂU 11
SELECT DISTINCT NV.MANV, TEN
FROM NHANVIEN NV, PHANCONG PC, LICHBAY LB
WHERE NV.MANV = PC.MANV 
AND PC.MACB = LB.MACB 
AND PC.MACB = '100' 
AND LB.NGAYDI = '2000/11/01'
AND NV.LOAINV = 1

-- CÂU 12
SELECT PC.MACB, NV.MANV, TEN
FROM NHANVIEN NV, PHANCONG PC,LICHBAY LB, CHUYENBAY CB
WHERE NV.MANV = PC.MANV 
AND PC.MACB = CB.MACB 
AND LB.MACB = CB.MACB 
AND LB.NGAYDI = '2000/10/31'
AND CB.SBDI = 'MIA' 
AND CB.GIODI = '20:30'

-- CÂU 13
SELECT PC.MACB, MB.SOHIEU, LMB.MALOAI, HANGSX
FROM LOAIMB LMB, MAYBAY MB, LICHBAY LB, PHANCONG PC, NHANVIEN NV
WHERE NV.MANV = PC.MANV 
AND PC.MACB = LB.MACB 
AND PC.NGAYDI = LB.NGAYDI 
AND LB.MALOAI = MB.MALOAI
AND MB.MALOAI = LMB.MALOAI 
AND NV.TEN = 'Quang'
AND NV.LOAINV = 1

-- CÂU 14
SELECT DISTINCT TEN
FROM NHANVIEN NV, PHANCONG PC
WHERE NV.MANV <> PC.MANV
AND LOAINV = 1

-- CÂU 15
SELECT DISTINCT TEN
FROM KHACHHANG KH, DATCHO DC, LICHBAY LB, MAYBAY MB, LOAIMB LMB
WHERE KH.MAKH = DC.MAKH
AND DC.MACB = LB.MACB
AND DC.NGAYDI = LB.NGAYDI
AND LB.MALOAI = MB.MALOAI
AND LB.SOHIEU = MB.SOHIEU
AND MB.MALOAI = LMB.MALOAI
AND LMB.HANGSX = 'Boeing'

-- CÂU 16
SELECT DISTINCT CB.MACB
FROM LICHBAY LB, CHUYENBAY CB, MAYBAY MB
WHERE LB.MACB = CB.MACB
AND LB.MALOAI = MB.MALOAI
AND LB.SOHIEU = MB.SOHIEU
AND MB.SOHIEU = 10
AND MB.MALOAI = 'B747'